# @Author: andreasprietzel
# @Date:   1970-01-01T01:00:00+01:00
# @Last modified by:   andreasprietzel
# @Last modified time: 2020-08-02T17:25:35+02:00

backend_savennpagespeedprofilerresult:
    path:     /savennpagespeedprofilerresult
    defaults:
        _controller: NNPageSpeedProfilerBundle:Backend:savennpagespeedprofilerresult
        _scope: backend
        _token_check: false
    methods: [POST]
    requirements:
        id: '.*'
        strategy: '.*'
        score: '.*'
        response: '.*'
        timestamp: '.*'
